server.port=9090
spring.ai.google.genai.api-key=AQ.Ab8RN6JbI4RKyDEUwfj4jWo3BOTW060ebDoneg85uiTAXOilcQ
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
 # Enable Circuit Breaker for Feign
spring.cloud.openfeign.circuitbreaker.enabled=true

# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.resumeService.sliding-window-size=5
resilience4j.circuitbreaker.instances.resumeService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.resumeService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.resumeService.wait-duration-in-open-state=100s
resilience4j.circuitbreaker.instances.resumeService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.resumeService.automatic-transition-from-open-to-half-open-enabled=true

